firstapp/urls.py
from django.conf.urls import url, include
from django.views.decorators.cache import cache_page

from rest_framework.routers import DefaultRouter

from . import views


# App namespace
app_name = "firstapp"


# Create a router to automatically create REST urls
router = DefaultRouter()
router.register(r'message', views.RestMessageView)
router.register(r'author', views.RestAuthorView)


urlpatterns = [
    # Views
    url(r'^$', cache_page(60 * 15)(views.index), name='index'),  # index page
    url(r'^message/(?P<message_id>[0-9]+)/$', cache_page(60 * 15)(views.message_detail), name='message-detail'),  # message detail page
    url(r'^author/(?P<author_id>[0-9]+)/$', cache_page(60 * 15)(views.author_detail), name='author-detail'),  # author detail page

    # User logging
    url(r'^logout$', views.logout_user, name='logout'),
    url('', include('social_django.urls', namespace='social')),

    # REST framework
    url(r'^rest/', include(router.urls, namespace='rest')),
    url(r'^rest/', router.get_api_root_view(), name="rest"),

]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^firstapp/', include('firstapp.urls')),
]

firstapp/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Author(AbstractUser):
    """
    User with default user fields and a timezone.
    """

    timezone = models.CharField(max_length=50, default='Europe/Paris')


class Message(models.Model):
    """
    Message with an author (user), a text and a publication date.
    """

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    message_text = models.CharField('message', max_length=140)
    publication_date = models.DateTimeField('publication date')

    def __str__(self):
        return str(self.publication_date) \
               + " " + str(self.message_text)

    def was_published_today(self):
        return self.publication_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_today.admin_order_field = 'publication_date'
    was_published_today.boolean = True
    was_published_today.short_description = 'Published today?'

firstapp/views.py
import datetime
import logging
import requests
import pytz

from django.contrib.auth import logout
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.utils.translation import gettext

from rest_framework import permissions, viewsets
from rest_framework.response import Response
from rest_framework.reverse import reverse

from .models import Message, Author
from .permissions import IsAuthorOrAdminOrReadOnly
from .serializers import MessageSerializer, AuthorSerializer


logger = logging.getLogger("firstapp")


####################
# Views
####################


def index(request):
    """
    View for index.html page.
    """
    return render(request, 'firstapp/index.html')


def message_detail(request, message_id):
    """
    View for message.html page.
    """
    return render(request, 'firstapp/message.html', {'message_id': message_id})


def author_detail(request, author_id):
    """
    View for author.html page.
    """
    # give data to the template
    author = get_object_or_404(Author, id=author_id)
    context = {
        'author': author,
        'timezones': pytz.common_timezones,
    }

    # If the timezone form is submitted (by an admin)
    try:
        if request.method == 'POST':
            if request.user.is_staff:
                timezone = request.POST['timezone']
                author.timezone = timezone
                author.save()
                logging.info("Timezone updated for %s by %s" % (author.username, request.user.username))
                # add info to the template
                # Translators: Toast message when timezone is successfully updated
                context['info'] = gettext("Timezone updated :)")
            else:
                logging.info("WARNING: a non-admin user (%s) try to update the timezone for %s" % (author.username, request.user.username))
    except Exception as e:
        logging.info("ERROR: exception while updating the timezone: %s" % e)
    return render(request, 'firstapp/author.html', context)


####################
# Actions
####################


def logout_user(request):
    """
    Log out the connected user.
    """

    logout(request)
    return HttpResponseRedirect(reverse("firstapp:index"))


####################
# REST framework
####################


class RestMessageView(viewsets.ModelViewSet):
    """
    REST API message view. Edit available for connected authors or admins.
    """

    queryset = Message.objects.all()
    serializer_class = MessageSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsAuthorOrAdminOrReadOnly,)

    def create(self, request, *args, **kwargs):
        """
        Validate the data in order to create the object.
        """
        logger.info('Message.create')

        # check if the user is logged in
        if request.user.is_authenticated:
            get_object_or_404(Author, id=request.user.id)
            return super().create(request, *args, **kwargs)
        else:
            raise ValueError("No user is logged in")

    def perform_create(self, serializer):
        """
        Perform the object creation.
        """
        logger.info('Message.perform_create')

        # Add the author and the publication date
        serializer.save(author=self.request.user, publication_date=datetime.datetime.now())
        logger.info('New message saved')
        # Notify tornado
        r = requests.post('http://localhost:1234/message_update', data={'event': 'create'})
        logger.info('Tornado notified: %s' % r.status_code)

    def list(self, request, *args, **kwargs):
        """
        Return the list all of messages. Diff with get_queryset ?
        """
        logger.info('Message.list')

        # get the message list or a text when no one are available
        message_list = super().list(request, *args, **kwargs)
        if len(message_list.data) == 0:
            # Translators: Text displayed on index.html when there are no messages
            return Response(gettext('No messages are available.'))
        else:
            return message_list

    def get_queryset(self):
        """
        Return the list all of messages. Diff with list ?
        """
        logger.info('Message.get_queryset')
        return super().get_queryset().order_by('-publication_date')

    def destroy(self, request, *args, **kwargs):
        """
        Validate the data in order to delete the object.
        """
        logger.info('Message.destroy')
        return super().destroy(request, *args, **kwargs)

    def perform_destroy(self, instance):
        """
        Perform the object deletion.
        """
        logger.info('Message.perform_destroy')

        # check if the user is logged in
        if self.request.user.is_authenticated:
            # check if this is the author or an admin
            author = get_object_or_404(Author, id=self.request.user.id)
            if author.id == instance.author.id or author.is_staff:
                # delete the message
                super().perform_destroy(instance)
                # Notify tornado
                r = requests.post('http://localhost:1234/message_update', data={'event': 'delete'})
                logger.info('Tornado notified: %s' % r.status_code)
            else:
                raise ValueError("The logged user is not an admin or the author")
        else:
            raise ValueError("No user is logged in")


class RestAuthorView(viewsets.ModelViewSet):
    """
    REST API author view.
    """

    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

firstapp/templates/firstapp/author.html
{% extends 'firstapp/base.html' %}

{% load i18n %}


{% block title %}
    {# Translators: Author page title #}
    {% trans "Author page" %}
{% endblock %}


{% block subtitle %}
    {{ author.username }}
{% endblock %}


{% block content %}

    <div class="section">

        <p>{{ author.first_name }} {{ author.last_name }}</p>
        <p>{{ author.email }}</p>
        <p>{{ author.timezone }}</p>

    </div>


    {% if user.is_authenticated and user.is_staff %}
        <div class="section">

            <form action="{% url 'firstapp:author-detail' author.id %}" method="POST" class="col s12">
                {% csrf_token %}

                {# Translators: Timezone form select label #}
                <label for="timezone">{% trans "Update your timezone" %}</label>

                <select name="timezone" id="timezone">
                    {% for timezone in timezones %}
                        <option value="{{ timezone }}" {% if timezone == author.timezone %} disabled selected {% endif %}>
                            {{ timezone }}
                        </option>
                    {% endfor %}
                </select>

                {# Translators: Timezone form button #}
                <input type="submit" value="{% trans 'Update' %}" class="btn waves-effect waves-light" />

            </form>
        </div>
    {% endif %}


    <!-- Snackbar -->
    <div id="snackbar"></div>

{% endblock content %}


{% block javascript %}

    <script type="text/javascript">

        // When the page is fully loaded
        $(document).ready(function() {

            // Init the form
            $('select').material_select();

            // Get the snackbar
            var snackbar = $("#snackbar");

            // If the timezone has just been updated
            {% if info %}
                snackbar.html("{{ info }}");
                snackbar.toggleClass("show");
                setTimeout(function(){ snackbar.toggleClass("show"); }, 3000);
            {% endif %}

        });

    </script>

{% endblock javascript %}

firstapp/templates/firstapp/base.html
{% load static %}

{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
        {# Translators: Project title #}
        {% trans "Madafaka" %}
    </title>

    <!-- Google Icon Font -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'firstapp/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- Materialize -->
    <link type="text/css" rel="stylesheet" href="{% static 'firstapp/css/materialize.min.css' %}"  media="screen,projection"/>
    <!-- Snackbar -->
    <link rel="stylesheet" type="text/css" href="{% static 'firstapp/css/snackbar.css' %}" />

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>


<body>

{# Nav + menu #}
<nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container">

        {# Nav title #}
        <a id="logo-container" href="{% url 'firstapp:index' %}" class="brand-logo">
            {# Translators: Project title #}
            {% trans "Madafaka" %}
        </a>

        {# Desktop nav menu (when full witdh #}
        <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
                {% if user.first_name or user.last_name %}
                    <li>
                        <a href="{% url 'firstapp:author-detail' user.id %}">
                            {{ user.first_name }} {{ user.last_name }}
                        </a>
                    </li>
                {% endif %}
                <li>
                    <a href="{% url 'firstapp:author-detail' user.id %}">{{ user.email }}</a>
                </li>
                <li>
                    <a href="{% url 'firstapp:logout' %}">
                        {# Translators: Log out text #}
                        {% trans "Log out" %}
                    </a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'firstapp:social:begin' 'google-oauth2' %}">
                        {# Translators: Log in text #}
                        {% trans "Log in" %}
                    </a>
                </li>
            {% endif %}
        </ul>

        {# Mobile nav menu (when no full witdh #}
        <ul id="nav-mobile" class="side-nav">
            {% if user.is_authenticated %}
                {% if user.first_name or user.last_name %}
                    <li>
                        <a href="{% url 'firstapp:author-detail' user.id %}">
                            {{ user.first_name }} {{ user.last_name }}
                        </a>
                    </li>
                {% endif %}
                <li>
                    <a href="{% url 'firstapp:author-detail' user.id %}">{{ user.email }}</a>
                </li>
                <li>
                    <a href="{% url 'firstapp:logout' %}">
                        {# Translators: Log out text #}
                        {% trans "Log out" %}
                    </a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'firstapp:social:begin' 'google-oauth2' %}">
                        {# Translators: Log in text #}
                        {% trans "Log in" %}
                    </a>
                </li>
            {% endif %}
        </ul>

        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
</nav>


{# Content #}
<div class="container">

    {# Title & subtitle #}
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center orange-text">

                {% block title %}
                {% endblock %}

            </h1>
            <div class="row center">
                <h5 class="header col s12 light">

                    {% block subtitle %}
                    {% endblock %}

                </h5>
            </div>
        </div>
    </div>

    {# Page content #}
    {% block content %}
    {% endblock %}

</div>


{# Footer #}
<div><br><br></div>
<footer class="page-footer orange">
    <div class="container">
        <div class="row">

            <div class="col s6">
                <h5 class="white-text">
                    {# Translators: Project title #}
                    {% trans "Madafaka" %}
                </h5>
                <p class="grey-text text-lighten-4">
                    {# Translators: Project subtitle #}
                    {% trans "A simple Django project. Biatch." %}
                </p>
            </div>


            <div class="col s6">
                <h5 class="white-text">Settings</h5>
                <ul>
                    <li><a class="white-text" href="{% url "admin:index" %}">Admin Django</a></li>
                    <li><a class="white-text" href="{% url "firstapp:rest" %}">API REST</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="orange-text text-lighten-3">FloZone</a>
        </div>
    </div>
</footer>


{# JS part #}
<script type="text/javascript" src="{% static 'firstapp/js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'firstapp/js/materialize.js' %}"></script>
<script type="text/javascript" src="{% static 'firstapp/js/init-materialize.js' %}"></script>
<script type="text/javascript">
    // CSRF TOKEN

    // In order to use a CSRF token with ajax requests
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
</script>


{% block javascript %}
{% endblock %}


</body>
</html>

firstapp/templates/firstapp/index.html
{% extends 'firstapp/base.html' %}

{% load i18n %}


{% block title %}
    {# Translators: Index title #}
    {% trans "Hello World!" %}
{% endblock %}


{% block subtitle %}
    {# Translators: Project subtitle #}
    {% trans "A simple Django project. Biatch." %}
{% endblock %}


{% block content %}

    {# Message list #}
    <div class="section">
        <div class="row" id="message_container">

        </div>
    </div>

    {# Post form #}
    <div class="section">
        {# TODO div propre en rouge #}
        <p id="result"></p>

        {% if user.is_authenticated %}
            <form id="post_form" class="col s12">
                <label for="message_text">
                    {# Translators: Post message form: label for input text #}
                    {% trans "New message" %}
                </label>

                {% csrf_token %}
                {# Translators: Post message form: placeholder for input text #}
                <input type="text" placeholder="{% trans "Your message text" %}" name="message_text" id="message_text" maxlength="140" data-length="140" class="validate"/>

                {# Translators: Post message form: submit button label{% endcomment #}
                <input type="submit" value="{% trans "Send" %}" class="btn waves-effect waves-light"/>
            </form>
        {% endif %}
    </div>

    {# Snackbar #}
    <div id="snackbar"></div>

{% endblock content %}


{% block javascript %}

    <script type="text/javascript">
        // AJAX

        // When the page is fully loaded
        $(document).ready(function() {
            // Get the snackbar
            var snackbar = $("#snackbar");

            // Load the message list
            get_message_list();

            // Connect to Tornado
            ws = new WebSocket("ws://localhost:1234/ws");

            ws.onmessage = function(evt) {
                console.log("Websocket: receive: " + evt.data);
                if(evt.data.startsWith("message_update")) {

                    var eventMessage;
                    var event = evt.data.replace("message_update_", "");
                    if(event === "create") {
                        {# TODO trad #}
                        eventMessage = "New message :)";
                    }
                    else if(event === "delete") {
                        {# TODO trad #}
                        eventMessage = "A message was deleted :(";
                    }
                    else {
                        eventMessage = "Unknown"
                    }

                    // Snackbar
                    snackbar.html(eventMessage);
                    snackbar.toggleClass("show");
                    setTimeout(function(){ snackbar.toggleClass("show"); }, 3000);

                    get_message_list();
                }
            };

            ws.onclose = function(evt) {
                console.log("Websocket: onclose");
            };

            ws.onopen = function(evt) {
                console.log("Websocket: onopen");
                var send = "ping";
                console.log("Websocket: send: " + send);
                ws.send(send);
            };

        });

        // Get the message list and display it
        var get_message_list = function () {
            console.log("get message list")
            $.ajax({
                type: "get",
                url: "{% url 'firstapp:rest:message-list' %}",
                success: function(data) {
                    var content = "";

                    // If there is no message
                    if(typeof data === "string") {
                        content = data;
                    }
                    // If there is a list of messages
                    else {
                        for(var i = 0; i < data.length; ++i) {

                            content += ""
                                + "<div class=\"col l6 m12\">"
                                + "<div class=\"card hoverable grey lighten-5 z-depth-1\">"
                                + "<div class=\"card-content truncate\">"
                                + "<p><b>"
                                + data[i].publication_date
                                + "</b><br>"
                                + "<br>"
                                + data[i].message_text
                                + "</p>";

                            {# If the user is allowed to delete the message #}
                            {% if user.is_authenticated %}
                                if( data[i].link.delete ) {
                                    content +=
                                        "<button rel=\"" + data[i].link.delete + "\" class=\"btn-floating halfway-fab waves-effect waves-light red\">"
                                        + "<i class=\"material-icons\">delete</i>" +
                                        + "</button>"
                                }
                            {% endif %}

                            content +=
                                "</div>"
                                + "<div class=\"card-action\">"
                                {# TODO trad #}
                                + "<a href=\"" + data[i].link.detail + "\">Details</a>"
                                + "</div></div></div>";

                        }
                    }
                    // Display the content
                    $('#message_container').html(content);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    $('#result').html(jqXHR.responseText);
                }
            });
        };

        // When an user submit the form, post the message
        var post_form = $('#post_form');
        post_form.submit(function(event) {
            event.preventDefault();
            $.ajax({
                type: "post",
                data: post_form.serialize(),
                url: "{% url 'firstapp:rest:message-list' %}",
                success: function(response) {
                    $('#result').html("");
                    $('#message_text').val("");
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    $('#result').html(jqXHR.responseText);
                }
            });
            return false;
        });

        // Click on a delete button
        $('#message_container').on('click', 'button', function () {
            var url = $(this).attr('rel');

            $.ajax({
                type: "delete",
                url: url,
                // Set CSRF token
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                },
                success: function(response) {
                    $('#result').html("");
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    $('#result').html(jqXHR.responseText);
                }
            });
        });

    </script>

{% endblock javascript %}

firstapp/templates/firstapp/message.html
{% extends 'firstapp/base.html' %}

{% load i18n %}


{% block title %}
    {# Translators: Detail page title #}
    {% trans "Details" %}
{% endblock %}


{% block content %}

    <div class="section">

        <div class="row">
            <div class="col s4">
                <p id="publication_date">
                </p>
            </div>

            <div class="col s4">
                <p id="author">
                </p>
            </div>
        </div>

        <div class="row">
            <div class="col s12">
                <div class="card-panel">
                    <p id="message_text">
                        {{ message.message_text }}
                    </p>
                </div>
            </div>
        </div>

    </div>

    <div class="section" id="delete_container">
    </div>

{% endblock content %}


{% block javascript %}

    <script type="text/javascript">

        // When the page is fully loaded
        $(document).ready(function() {

            // Load the message detail
            get_message();

        });


        // Get the message and display it
        var get_message = function () {
            var url = "{% url 'firstapp:rest:message-detail' '12345' %}".replace(/12345/, {{ message_id }});

            $.ajax({
                type: "get",
                url: url,
                success: function(data) {

                    $("#publication_date").html(data.publication_date);
                    $("#message_text").html(data.message_text);

                    {% if user.is_authenticated %}
                        if( data.link.delete ) {
                            var content =
                                "<button id=\"delete\" rel=\"" + data.link.delete + "\" class=\"btn waves-effect waves-light\" >"
                                + "<i class=\"material-icons left\">delete</i>"
                                + "Delete"
                                + "</button>";
                            $('#delete_container').append(content);
                        }
                    {% endif %}

                    get_author(data.author);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    $('#message_text').html(jqXHR.responseText);
                }
            });
        };


        // Get the message author and display it
        var get_author = function (userId) {
            var restUrl = "{% url 'firstapp:rest:author-detail' '12345' %}".replace(/12345/, userId);
            var userUrl = "{% url 'firstapp:author-detail' '12345' %}".replace(/12345/, userId);

            $.ajax({
                type: "get",
                url: restUrl,
                success: function(data) {
                    var usernameContent = "<a href=\"" + userUrl + "\">" + data.username + "</a>";
                    $("#author").html(usernameContent);
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    $('#message_text').html(jqXHR.responseText);
                }
            });
        };


        // Click on a delete button
        $('#message_container').on('click', 'button', function () {
            var url = $(this).attr('rel');

            $.ajax({
                type: "delete",
                url: url,
                // Set CSRF token
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                },
                success: function(response) {
                    // Redirect to the home page
                    window.location.replace("{% url 'firstapp:index' %}");
                },
                error: function(jqXHR, textStatus, errorThrown) {
                    console.log(jqXHR.responseText);
                }
            });
        });

    </script>

{% endblock javascript %}